import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "@/components/Sidebar/Sidebar";
import Navbar from "@/components/Navbar/Navbar";
import { SidebarProvider } from "@/context/SidebarContext";
import { ModalProvider } from "@/context/ModalBackgroundContext";
import ModalBlackScreen from "@/components/ModalBlackScreen";
import { ChatProvider } from "@/context/ChatContext";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
} from '@clerk/nextjs'
import SigninNavbar from "@/components/Navbar/SigninNavbar";

export const metadata: Metadata = {
  title: "ChatGPT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <ChatProvider>
          <SidebarProvider>
            <ModalProvider>
              <body
                className={`flex`}
              >
                <SignedIn>
                  <div className="h-[100dvh]">
                    <Sidebar />
                  </div>
                </SignedIn>
                <ModalBlackScreen />
                <div className="w-full flex flex-col max-h-[100dvh]">
                  <SignedIn>
                    <Navbar />
                  </SignedIn>
                  <SignedOut>
                    <SigninNavbar/>
                  </SignedOut>
                  {children}
                </div>
              </body>
            </ModalProvider>
          </SidebarProvider>
        </ChatProvider>
      </html>
    </ClerkProvider>
  );
}
